//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace aspx_site.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class novamainEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new novamainEntities object using the connection string found in the 'novamainEntities' section of the application configuration file.
        /// </summary>
        public novamainEntities() : base("name=novamainEntities", "novamainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new novamainEntities object.
        /// </summary>
        public novamainEntities(string connectionString) : base(connectionString, "novamainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new novamainEntities object.
        /// </summary>
        public novamainEntities(EntityConnection connection) : base(connection, "novamainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<appinfo> appinfoes
        {
            get
            {
                if ((_appinfoes == null))
                {
                    _appinfoes = base.CreateObjectSet<appinfo>("appinfoes");
                }
                return _appinfoes;
            }
        }
        private ObjectSet<appinfo> _appinfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<appuser> appusers
        {
            get
            {
                if ((_appusers == null))
                {
                    _appusers = base.CreateObjectSet<appuser>("appusers");
                }
                return _appusers;
            }
        }
        private ObjectSet<appuser> _appusers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comment> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comment>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comment> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<novaevent> novaevents
        {
            get
            {
                if ((_novaevents == null))
                {
                    _novaevents = base.CreateObjectSet<novaevent>("novaevents");
                }
                return _novaevents;
            }
        }
        private ObjectSet<novaevent> _novaevents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lastupdate> lastupdates
        {
            get
            {
                if ((_lastupdates == null))
                {
                    _lastupdates = base.CreateObjectSet<lastupdate>("lastupdates");
                }
                return _lastupdates;
            }
        }
        private ObjectSet<lastupdate> _lastupdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<message> messages
        {
            get
            {
                if ((_messages == null))
                {
                    _messages = base.CreateObjectSet<message>("messages");
                }
                return _messages;
            }
        }
        private ObjectSet<message> _messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rsvp> rsvps
        {
            get
            {
                if ((_rsvps == null))
                {
                    _rsvps = base.CreateObjectSet<rsvp>("rsvps");
                }
                return _rsvps;
            }
        }
        private ObjectSet<rsvp> _rsvps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<beta_events> beta_events
        {
            get
            {
                if ((_beta_events == null))
                {
                    _beta_events = base.CreateObjectSet<beta_events>("beta_events");
                }
                return _beta_events;
            }
        }
        private ObjectSet<beta_events> _beta_events;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<server_logs> server_logs
        {
            get
            {
                if ((_server_logs == null))
                {
                    _server_logs = base.CreateObjectSet<server_logs>("server_logs");
                }
                return _server_logs;
            }
        }
        private ObjectSet<server_logs> _server_logs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the appinfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToappinfoes(appinfo appinfo)
        {
            base.AddObject("appinfoes", appinfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the appusers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToappusers(appuser appuser)
        {
            base.AddObject("appusers", appuser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comment comment)
        {
            base.AddObject("comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the novaevents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTonovaevents(novaevent novaevent)
        {
            base.AddObject("novaevents", novaevent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lastupdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolastupdates(lastupdate lastupdate)
        {
            base.AddObject("lastupdates", lastupdate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomessages(message message)
        {
            base.AddObject("messages", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rsvps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorsvps(rsvp rsvp)
        {
            base.AddObject("rsvps", rsvp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the beta_events EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobeta_events(beta_events beta_events)
        {
            base.AddObject("beta_events", beta_events);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the server_logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToserver_logs(server_logs server_logs)
        {
            base.AddObject("server_logs", server_logs);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="appinfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class appinfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new appinfo object.
        /// </summary>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="hashedAppID">Initial value of the HashedAppID property.</param>
        /// <param name="appName">Initial value of the AppName property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static appinfo Createappinfo(global::System.Int32 appID, global::System.String hashedAppID, global::System.String appName, global::System.Int32 customerID)
        {
            appinfo appinfo = new appinfo();
            appinfo.AppID = appID;
            appinfo.HashedAppID = hashedAppID;
            appinfo.AppName = appName;
            appinfo.CustomerID = customerID;
            return appinfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                if (_AppID != value)
                {
                    OnAppIDChanging(value);
                    ReportPropertyChanging("AppID");
                    _AppID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AppID");
                    OnAppIDChanged();
                }
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HashedAppID
        {
            get
            {
                return _HashedAppID;
            }
            set
            {
                OnHashedAppIDChanging(value);
                ReportPropertyChanging("HashedAppID");
                _HashedAppID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HashedAppID");
                OnHashedAppIDChanged();
            }
        }
        private global::System.String _HashedAppID;
        partial void OnHashedAppIDChanging(global::System.String value);
        partial void OnHashedAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AppName
        {
            get
            {
                return _AppName;
            }
            set
            {
                OnAppNameChanging(value);
                ReportPropertyChanging("AppName");
                _AppName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AppName");
                OnAppNameChanged();
            }
        }
        private global::System.String _AppName;
        partial void OnAppNameChanging(global::System.String value);
        partial void OnAppNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeScreenText
        {
            get
            {
                return _HomeScreenText;
            }
            set
            {
                OnHomeScreenTextChanging(value);
                ReportPropertyChanging("HomeScreenText");
                _HomeScreenText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeScreenText");
                OnHomeScreenTextChanged();
            }
        }
        private global::System.String _HomeScreenText;
        partial void OnHomeScreenTextChanging(global::System.String value);
        partial void OnHomeScreenTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterAccessToken
        {
            get
            {
                return _TwitterAccessToken;
            }
            set
            {
                OnTwitterAccessTokenChanging(value);
                ReportPropertyChanging("TwitterAccessToken");
                _TwitterAccessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterAccessToken");
                OnTwitterAccessTokenChanged();
            }
        }
        private global::System.String _TwitterAccessToken;
        partial void OnTwitterAccessTokenChanging(global::System.String value);
        partial void OnTwitterAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterAccessTokenSecret
        {
            get
            {
                return _TwitterAccessTokenSecret;
            }
            set
            {
                OnTwitterAccessTokenSecretChanging(value);
                ReportPropertyChanging("TwitterAccessTokenSecret");
                _TwitterAccessTokenSecret = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterAccessTokenSecret");
                OnTwitterAccessTokenSecretChanged();
            }
        }
        private global::System.String _TwitterAccessTokenSecret;
        partial void OnTwitterAccessTokenSecretChanging(global::System.String value);
        partial void OnTwitterAccessTokenSecretChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookAccessToken
        {
            get
            {
                return _FacebookAccessToken;
            }
            set
            {
                OnFacebookAccessTokenChanging(value);
                ReportPropertyChanging("FacebookAccessToken");
                _FacebookAccessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookAccessToken");
                OnFacebookAccessTokenChanged();
            }
        }
        private global::System.String _FacebookAccessToken;
        partial void OnFacebookAccessTokenChanging(global::System.String value);
        partial void OnFacebookAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookPageId
        {
            get
            {
                return _FacebookPageId;
            }
            set
            {
                OnFacebookPageIdChanging(value);
                ReportPropertyChanging("FacebookPageId");
                _FacebookPageId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookPageId");
                OnFacebookPageIdChanged();
            }
        }
        private global::System.String _FacebookPageId;
        partial void OnFacebookPageIdChanging(global::System.String value);
        partial void OnFacebookPageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookPageAccessToken
        {
            get
            {
                return _FacebookPageAccessToken;
            }
            set
            {
                OnFacebookPageAccessTokenChanging(value);
                ReportPropertyChanging("FacebookPageAccessToken");
                _FacebookPageAccessToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookPageAccessToken");
                OnFacebookPageAccessTokenChanged();
            }
        }
        private global::System.String _FacebookPageAccessToken;
        partial void OnFacebookPageAccessTokenChanging(global::System.String value);
        partial void OnFacebookPageAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TwitterUserId
        {
            get
            {
                return _TwitterUserId;
            }
            set
            {
                OnTwitterUserIdChanging(value);
                ReportPropertyChanging("TwitterUserId");
                _TwitterUserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TwitterUserId");
                OnTwitterUserIdChanged();
            }
        }
        private global::System.String _TwitterUserId;
        partial void OnTwitterUserIdChanging(global::System.String value);
        partial void OnTwitterUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookUserId
        {
            get
            {
                return _FacebookUserId;
            }
            set
            {
                OnFacebookUserIdChanging(value);
                ReportPropertyChanging("FacebookUserId");
                _FacebookUserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookUserId");
                OnFacebookUserIdChanged();
            }
        }
        private global::System.String _FacebookUserId;
        partial void OnFacebookUserIdChanging(global::System.String value);
        partial void OnFacebookUserIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="appuser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class appuser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new appuser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="handsetID">Initial value of the HandsetID property.</param>
        public static appuser Createappuser(global::System.Int32 userID, global::System.Int32 appID, global::System.String handsetID)
        {
            appuser appuser = new appuser();
            appuser.UserID = userID;
            appuser.AppID = appID;
            appuser.HandsetID = handsetID;
            return appuser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HandsetID
        {
            get
            {
                return _HandsetID;
            }
            set
            {
                OnHandsetIDChanging(value);
                ReportPropertyChanging("HandsetID");
                _HandsetID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HandsetID");
                OnHandsetIDChanged();
            }
        }
        private global::System.String _HandsetID;
        partial void OnHandsetIDChanging(global::System.String value);
        partial void OnHandsetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HandsetModel
        {
            get
            {
                return _HandsetModel;
            }
            set
            {
                OnHandsetModelChanging(value);
                ReportPropertyChanging("HandsetModel");
                _HandsetModel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HandsetModel");
                OnHandsetModelChanged();
            }
        }
        private global::System.String _HandsetModel;
        partial void OnHandsetModelChanging(global::System.String value);
        partial void OnHandsetModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HandsetManufacturer
        {
            get
            {
                return _HandsetManufacturer;
            }
            set
            {
                OnHandsetManufacturerChanging(value);
                ReportPropertyChanging("HandsetManufacturer");
                _HandsetManufacturer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HandsetManufacturer");
                OnHandsetManufacturerChanged();
            }
        }
        private global::System.String _HandsetManufacturer;
        partial void OnHandsetManufacturerChanging(global::System.String value);
        partial void OnHandsetManufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HandsetProduct
        {
            get
            {
                return _HandsetProduct;
            }
            set
            {
                OnHandsetProductChanging(value);
                ReportPropertyChanging("HandsetProduct");
                _HandsetProduct = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HandsetProduct");
                OnHandsetProductChanged();
            }
        }
        private global::System.String _HandsetProduct;
        partial void OnHandsetProductChanging(global::System.String value);
        partial void OnHandsetProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserEmail
        {
            get
            {
                return _UserEmail;
            }
            set
            {
                OnUserEmailChanging(value);
                ReportPropertyChanging("UserEmail");
                _UserEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserEmail");
                OnUserEmailChanged();
            }
        }
        private global::System.String _UserEmail;
        partial void OnUserEmailChanging(global::System.String value);
        partial void OnUserEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserFirstName
        {
            get
            {
                return _UserFirstName;
            }
            set
            {
                OnUserFirstNameChanging(value);
                ReportPropertyChanging("UserFirstName");
                _UserFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserFirstName");
                OnUserFirstNameChanged();
            }
        }
        private global::System.String _UserFirstName;
        partial void OnUserFirstNameChanging(global::System.String value);
        partial void OnUserFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserLastName
        {
            get
            {
                return _UserLastName;
            }
            set
            {
                OnUserLastNameChanging(value);
                ReportPropertyChanging("UserLastName");
                _UserLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserLastName");
                OnUserLastNameChanged();
            }
        }
        private global::System.String _UserLastName;
        partial void OnUserLastNameChanging(global::System.String value);
        partial void OnUserLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegisterTimestamp
        {
            get
            {
                return _RegisterTimestamp;
            }
            set
            {
                OnRegisterTimestampChanging(value);
                ReportPropertyChanging("RegisterTimestamp");
                _RegisterTimestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegisterTimestamp");
                OnRegisterTimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegisterTimestamp;
        partial void OnRegisterTimestampChanging(Nullable<global::System.DateTime> value);
        partial void OnRegisterTimestampChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="beta_events")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class beta_events : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new beta_events object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static beta_events Createbeta_events(global::System.Int32 id)
        {
            beta_events beta_events = new beta_events();
            beta_events.id = id;
            return beta_events;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_desc
        {
            get
            {
                return _event_desc;
            }
            set
            {
                Onevent_descChanging(value);
                ReportPropertyChanging("event_desc");
                _event_desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_desc");
                Onevent_descChanged();
            }
        }
        private global::System.String _event_desc;
        partial void Onevent_descChanging(global::System.String value);
        partial void Onevent_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String submitted_by
        {
            get
            {
                return _submitted_by;
            }
            set
            {
                Onsubmitted_byChanging(value);
                ReportPropertyChanging("submitted_by");
                _submitted_by = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("submitted_by");
                Onsubmitted_byChanged();
            }
        }
        private global::System.String _submitted_by;
        partial void Onsubmitted_byChanging(global::System.String value);
        partial void Onsubmitted_byChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col1
        {
            get
            {
                return _col1;
            }
            set
            {
                Oncol1Changing(value);
                ReportPropertyChanging("col1");
                _col1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col1");
                Oncol1Changed();
            }
        }
        private global::System.String _col1;
        partial void Oncol1Changing(global::System.String value);
        partial void Oncol1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col2
        {
            get
            {
                return _col2;
            }
            set
            {
                Oncol2Changing(value);
                ReportPropertyChanging("col2");
                _col2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col2");
                Oncol2Changed();
            }
        }
        private global::System.String _col2;
        partial void Oncol2Changing(global::System.String value);
        partial void Oncol2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col3
        {
            get
            {
                return _col3;
            }
            set
            {
                Oncol3Changing(value);
                ReportPropertyChanging("col3");
                _col3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col3");
                Oncol3Changed();
            }
        }
        private global::System.String _col3;
        partial void Oncol3Changing(global::System.String value);
        partial void Oncol3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col4
        {
            get
            {
                return _col4;
            }
            set
            {
                Oncol4Changing(value);
                ReportPropertyChanging("col4");
                _col4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col4");
                Oncol4Changed();
            }
        }
        private global::System.String _col4;
        partial void Oncol4Changing(global::System.String value);
        partial void Oncol4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col5
        {
            get
            {
                return _col5;
            }
            set
            {
                Oncol5Changing(value);
                ReportPropertyChanging("col5");
                _col5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col5");
                Oncol5Changed();
            }
        }
        private global::System.String _col5;
        partial void Oncol5Changing(global::System.String value);
        partial void Oncol5Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comment object.
        /// </summary>
        /// <param name="commentID">Initial value of the CommentID property.</param>
        /// <param name="eventID">Initial value of the EventID property.</param>
        /// <param name="comment1">Initial value of the Comment1 property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static comment Createcomment(global::System.Int32 commentID, global::System.Int32 eventID, global::System.String comment1, global::System.Int32 userID)
        {
            comment comment = new comment();
            comment.CommentID = commentID;
            comment.EventID = eventID;
            comment.Comment1 = comment1;
            comment.UserID = userID;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                OnEventIDChanging(value);
                ReportPropertyChanging("EventID");
                _EventID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventID");
                OnEventIDChanged();
            }
        }
        private global::System.Int32 _EventID;
        partial void OnEventIDChanging(global::System.Int32 value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment1
        {
            get
            {
                return _Comment1;
            }
            set
            {
                OnComment1Changing(value);
                ReportPropertyChanging("Comment1");
                _Comment1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comment1");
                OnComment1Changed();
            }
        }
        private global::System.String _Comment1;
        partial void OnComment1Changing(global::System.String value);
        partial void OnComment1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="lastupdate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lastupdate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lastupdate object.
        /// </summary>
        /// <param name="updateID">Initial value of the UpdateID property.</param>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="lastEventUpdate">Initial value of the LastEventUpdate property.</param>
        /// <param name="lastMessageUpdate">Initial value of the LastMessageUpdate property.</param>
        /// <param name="lastHomescreenUpdate">Initial value of the LastHomescreenUpdate property.</param>
        public static lastupdate Createlastupdate(global::System.Int32 updateID, global::System.Int32 appID, global::System.DateTime lastEventUpdate, global::System.DateTime lastMessageUpdate, global::System.DateTime lastHomescreenUpdate)
        {
            lastupdate lastupdate = new lastupdate();
            lastupdate.UpdateID = updateID;
            lastupdate.AppID = appID;
            lastupdate.LastEventUpdate = lastEventUpdate;
            lastupdate.LastMessageUpdate = lastMessageUpdate;
            lastupdate.LastHomescreenUpdate = lastHomescreenUpdate;
            return lastupdate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UpdateID
        {
            get
            {
                return _UpdateID;
            }
            set
            {
                if (_UpdateID != value)
                {
                    OnUpdateIDChanging(value);
                    ReportPropertyChanging("UpdateID");
                    _UpdateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UpdateID");
                    OnUpdateIDChanged();
                }
            }
        }
        private global::System.Int32 _UpdateID;
        partial void OnUpdateIDChanging(global::System.Int32 value);
        partial void OnUpdateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastEventUpdate
        {
            get
            {
                return _LastEventUpdate;
            }
            set
            {
                OnLastEventUpdateChanging(value);
                ReportPropertyChanging("LastEventUpdate");
                _LastEventUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEventUpdate");
                OnLastEventUpdateChanged();
            }
        }
        private global::System.DateTime _LastEventUpdate;
        partial void OnLastEventUpdateChanging(global::System.DateTime value);
        partial void OnLastEventUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastMessageUpdate
        {
            get
            {
                return _LastMessageUpdate;
            }
            set
            {
                OnLastMessageUpdateChanging(value);
                ReportPropertyChanging("LastMessageUpdate");
                _LastMessageUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastMessageUpdate");
                OnLastMessageUpdateChanged();
            }
        }
        private global::System.DateTime _LastMessageUpdate;
        partial void OnLastMessageUpdateChanging(global::System.DateTime value);
        partial void OnLastMessageUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastHomescreenUpdate
        {
            get
            {
                return _LastHomescreenUpdate;
            }
            set
            {
                OnLastHomescreenUpdateChanging(value);
                ReportPropertyChanging("LastHomescreenUpdate");
                _LastHomescreenUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastHomescreenUpdate");
                OnLastHomescreenUpdateChanged();
            }
        }
        private global::System.DateTime _LastHomescreenUpdate;
        partial void OnLastHomescreenUpdateChanging(global::System.DateTime value);
        partial void OnLastHomescreenUpdateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new message object.
        /// </summary>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="messageTitle">Initial value of the MessageTitle property.</param>
        /// <param name="messageContents">Initial value of the MessageContents property.</param>
        /// <param name="messageDate">Initial value of the MessageDate property.</param>
        public static message Createmessage(global::System.Int32 messageID, global::System.Int32 appID, global::System.String messageTitle, global::System.String messageContents, global::System.DateTime messageDate)
        {
            message message = new message();
            message.MessageID = messageID;
            message.AppID = appID;
            message.MessageTitle = messageTitle;
            message.MessageContents = messageContents;
            message.MessageDate = messageDate;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                if (_MessageID != value)
                {
                    OnMessageIDChanging(value);
                    ReportPropertyChanging("MessageID");
                    _MessageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MessageID");
                    OnMessageIDChanged();
                }
            }
        }
        private global::System.Int32 _MessageID;
        partial void OnMessageIDChanging(global::System.Int32 value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageTitle
        {
            get
            {
                return _MessageTitle;
            }
            set
            {
                OnMessageTitleChanging(value);
                ReportPropertyChanging("MessageTitle");
                _MessageTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageTitle");
                OnMessageTitleChanged();
            }
        }
        private global::System.String _MessageTitle;
        partial void OnMessageTitleChanging(global::System.String value);
        partial void OnMessageTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageContents
        {
            get
            {
                return _MessageContents;
            }
            set
            {
                OnMessageContentsChanging(value);
                ReportPropertyChanging("MessageContents");
                _MessageContents = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageContents");
                OnMessageContentsChanged();
            }
        }
        private global::System.String _MessageContents;
        partial void OnMessageContentsChanging(global::System.String value);
        partial void OnMessageContentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageDate
        {
            get
            {
                return _MessageDate;
            }
            set
            {
                OnMessageDateChanging(value);
                ReportPropertyChanging("MessageDate");
                _MessageDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageDate");
                OnMessageDateChanged();
            }
        }
        private global::System.DateTime _MessageDate;
        partial void OnMessageDateChanging(global::System.DateTime value);
        partial void OnMessageDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="novaevent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class novaevent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new novaevent object.
        /// </summary>
        /// <param name="eventID">Initial value of the EventID property.</param>
        /// <param name="syncID">Initial value of the SyncID property.</param>
        /// <param name="appID">Initial value of the AppID property.</param>
        /// <param name="eventName">Initial value of the EventName property.</param>
        /// <param name="eventDesc">Initial value of the EventDesc property.</param>
        /// <param name="eventStart">Initial value of the EventStart property.</param>
        /// <param name="attending">Initial value of the Attending property.</param>
        /// <param name="notAttending">Initial value of the NotAttending property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        /// <param name="eventEnd">Initial value of the EventEnd property.</param>
        /// <param name="disabled">Initial value of the Disabled property.</param>
        public static novaevent Createnovaevent(global::System.Int32 eventID, global::System.String syncID, global::System.Int32 appID, global::System.String eventName, global::System.String eventDesc, global::System.DateTime eventStart, global::System.Int32 attending, global::System.Int32 notAttending, global::System.DateTime lastUpdated, global::System.DateTime eventEnd, global::System.Int32 disabled)
        {
            novaevent novaevent = new novaevent();
            novaevent.EventID = eventID;
            novaevent.SyncID = syncID;
            novaevent.AppID = appID;
            novaevent.EventName = eventName;
            novaevent.EventDesc = eventDesc;
            novaevent.EventStart = eventStart;
            novaevent.Attending = attending;
            novaevent.NotAttending = notAttending;
            novaevent.LastUpdated = lastUpdated;
            novaevent.EventEnd = eventEnd;
            novaevent.Disabled = disabled;
            return novaevent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                if (_EventID != value)
                {
                    OnEventIDChanging(value);
                    ReportPropertyChanging("EventID");
                    _EventID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventID");
                    OnEventIDChanged();
                }
            }
        }
        private global::System.Int32 _EventID;
        partial void OnEventIDChanging(global::System.Int32 value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SyncID
        {
            get
            {
                return _SyncID;
            }
            set
            {
                OnSyncIDChanging(value);
                ReportPropertyChanging("SyncID");
                _SyncID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SyncID");
                OnSyncIDChanged();
            }
        }
        private global::System.String _SyncID;
        partial void OnSyncIDChanging(global::System.String value);
        partial void OnSyncIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppID
        {
            get
            {
                return _AppID;
            }
            set
            {
                OnAppIDChanging(value);
                ReportPropertyChanging("AppID");
                _AppID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppID");
                OnAppIDChanged();
            }
        }
        private global::System.Int32 _AppID;
        partial void OnAppIDChanging(global::System.Int32 value);
        partial void OnAppIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventName
        {
            get
            {
                return _EventName;
            }
            set
            {
                OnEventNameChanging(value);
                ReportPropertyChanging("EventName");
                _EventName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventName");
                OnEventNameChanged();
            }
        }
        private global::System.String _EventName;
        partial void OnEventNameChanging(global::System.String value);
        partial void OnEventNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventDesc
        {
            get
            {
                return _EventDesc;
            }
            set
            {
                OnEventDescChanging(value);
                ReportPropertyChanging("EventDesc");
                _EventDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventDesc");
                OnEventDescChanged();
            }
        }
        private global::System.String _EventDesc;
        partial void OnEventDescChanging(global::System.String value);
        partial void OnEventDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventStart
        {
            get
            {
                return _EventStart;
            }
            set
            {
                OnEventStartChanging(value);
                ReportPropertyChanging("EventStart");
                _EventStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventStart");
                OnEventStartChanged();
            }
        }
        private global::System.DateTime _EventStart;
        partial void OnEventStartChanging(global::System.DateTime value);
        partial void OnEventStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Attending
        {
            get
            {
                return _Attending;
            }
            set
            {
                OnAttendingChanging(value);
                ReportPropertyChanging("Attending");
                _Attending = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attending");
                OnAttendingChanged();
            }
        }
        private global::System.Int32 _Attending;
        partial void OnAttendingChanging(global::System.Int32 value);
        partial void OnAttendingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NotAttending
        {
            get
            {
                return _NotAttending;
            }
            set
            {
                OnNotAttendingChanging(value);
                ReportPropertyChanging("NotAttending");
                _NotAttending = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotAttending");
                OnNotAttendingChanged();
            }
        }
        private global::System.Int32 _NotAttending;
        partial void OnNotAttendingChanging(global::System.Int32 value);
        partial void OnNotAttendingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventEnd
        {
            get
            {
                return _EventEnd;
            }
            set
            {
                OnEventEndChanging(value);
                ReportPropertyChanging("EventEnd");
                _EventEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventEnd");
                OnEventEndChanged();
            }
        }
        private global::System.DateTime _EventEnd;
        partial void OnEventEndChanging(global::System.DateTime value);
        partial void OnEventEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Disabled
        {
            get
            {
                return _Disabled;
            }
            set
            {
                OnDisabledChanging(value);
                ReportPropertyChanging("Disabled");
                _Disabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Disabled");
                OnDisabledChanged();
            }
        }
        private global::System.Int32 _Disabled;
        partial void OnDisabledChanging(global::System.Int32 value);
        partial void OnDisabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="rsvp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rsvp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rsvp object.
        /// </summary>
        /// <param name="rsvpID">Initial value of the RsvpID property.</param>
        /// <param name="eventID">Initial value of the EventID property.</param>
        /// <param name="rsvp1">Initial value of the Rsvp1 property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static rsvp Creatersvp(global::System.Int32 rsvpID, global::System.Int32 eventID, global::System.String rsvp1, global::System.Int32 userID)
        {
            rsvp rsvp = new rsvp();
            rsvp.RsvpID = rsvpID;
            rsvp.EventID = eventID;
            rsvp.Rsvp1 = rsvp1;
            rsvp.UserID = userID;
            return rsvp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RsvpID
        {
            get
            {
                return _RsvpID;
            }
            set
            {
                if (_RsvpID != value)
                {
                    OnRsvpIDChanging(value);
                    ReportPropertyChanging("RsvpID");
                    _RsvpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RsvpID");
                    OnRsvpIDChanged();
                }
            }
        }
        private global::System.Int32 _RsvpID;
        partial void OnRsvpIDChanging(global::System.Int32 value);
        partial void OnRsvpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                OnEventIDChanging(value);
                ReportPropertyChanging("EventID");
                _EventID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventID");
                OnEventIDChanged();
            }
        }
        private global::System.Int32 _EventID;
        partial void OnEventIDChanging(global::System.Int32 value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rsvp1
        {
            get
            {
                return _Rsvp1;
            }
            set
            {
                OnRsvp1Changing(value);
                ReportPropertyChanging("Rsvp1");
                _Rsvp1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rsvp1");
                OnRsvp1Changed();
            }
        }
        private global::System.String _Rsvp1;
        partial void OnRsvp1Changing(global::System.String value);
        partial void OnRsvp1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="novaModel", Name="server_logs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class server_logs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new server_logs object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static server_logs Createserver_logs(global::System.Int32 id)
        {
            server_logs server_logs = new server_logs();
            server_logs.id = id;
            return server_logs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col1
        {
            get
            {
                return _col1;
            }
            set
            {
                Oncol1Changing(value);
                ReportPropertyChanging("col1");
                _col1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col1");
                Oncol1Changed();
            }
        }
        private global::System.String _col1;
        partial void Oncol1Changing(global::System.String value);
        partial void Oncol1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col2
        {
            get
            {
                return _col2;
            }
            set
            {
                Oncol2Changing(value);
                ReportPropertyChanging("col2");
                _col2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col2");
                Oncol2Changed();
            }
        }
        private global::System.String _col2;
        partial void Oncol2Changing(global::System.String value);
        partial void Oncol2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col3
        {
            get
            {
                return _col3;
            }
            set
            {
                Oncol3Changing(value);
                ReportPropertyChanging("col3");
                _col3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col3");
                Oncol3Changed();
            }
        }
        private global::System.String _col3;
        partial void Oncol3Changing(global::System.String value);
        partial void Oncol3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col4
        {
            get
            {
                return _col4;
            }
            set
            {
                Oncol4Changing(value);
                ReportPropertyChanging("col4");
                _col4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col4");
                Oncol4Changed();
            }
        }
        private global::System.String _col4;
        partial void Oncol4Changing(global::System.String value);
        partial void Oncol4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col5
        {
            get
            {
                return _col5;
            }
            set
            {
                Oncol5Changing(value);
                ReportPropertyChanging("col5");
                _col5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col5");
                Oncol5Changed();
            }
        }
        private global::System.String _col5;
        partial void Oncol5Changing(global::System.String value);
        partial void Oncol5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_desc
        {
            get
            {
                return _event_desc;
            }
            set
            {
                Onevent_descChanging(value);
                ReportPropertyChanging("event_desc");
                _event_desc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_desc");
                Onevent_descChanged();
            }
        }
        private global::System.String _event_desc;
        partial void Onevent_descChanging(global::System.String value);
        partial void Onevent_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col6
        {
            get
            {
                return _col6;
            }
            set
            {
                Oncol6Changing(value);
                ReportPropertyChanging("col6");
                _col6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col6");
                Oncol6Changed();
            }
        }
        private global::System.String _col6;
        partial void Oncol6Changing(global::System.String value);
        partial void Oncol6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String col7
        {
            get
            {
                return _col7;
            }
            set
            {
                Oncol7Changing(value);
                ReportPropertyChanging("col7");
                _col7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("col7");
                Oncol7Changed();
            }
        }
        private global::System.String _col7;
        partial void Oncol7Changing(global::System.String value);
        partial void Oncol7Changed();

        #endregion
    
    }

    #endregion
    
}
